import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Layout } from '../component/layout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
   const submitSearchDoctor = (event : any) => {
    event.preventDefault();

  }
  return (
      <Layout>
        <Head>
          <title>Prenez un rendez-vous chez doctolib</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <main>
        <h1 className={styles.title}>
          Réservez une consultation physique chez un professionnel de santé
        </h1>
        <div className="container" style={{textAlign:"center"}}>
          <form action="/Doctors">
            <label>
              <input type="text" name="name" placeholder = "Rechercher un médecin" />
            </label>
            <input type="submit" value="Submit" />
          </form>
          <div className={styles.grid}>
            <Link href="#">
            <a  className={styles.card}>
              <h2>Prenez un RDV &rarr;</h2>
              <p>prenez un rdv rapide avec votre médecin</p>
            </a>
            </Link>
            </div>
        </div>
      </main>
      </Layout>
  )
}

export default Home
